### ISSUE TITLE
[Bug]: ComfyUI Manager 500 error after fetching updates

### ISSUE THREAD

**Issue by aperepel** [Comfy-Org/desktop#1013]
### App Version

This has been happening with all desktop versions for the past month at least.

### Expected Behavior

Stable update cadence.

### Actual Behavior

It seems that every time a user clicks fetch update button, it breaks the desktop-installed comfyui manager on OSX. The error suggests it's checking for a git tag, but the desktop set it to the local path instead. As a result:

<img width="336" alt="Image" src="https://github.com/user-attachments/assets/a34b847e-4bd0-4048-8d2e-699b091a622c" />

```
File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 77, in get_comfyui_tag
    repo = git.Repo(comfy_path)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/agrande/ComfyUI/.venv/lib/python3.12/site-packages/git/repo/base.py", line 289, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Applications/ComfyUI.app/Contents/Resources/ComfyUI
```

### Steps to Reproduce

Install the desktop app, then fetch update. Maybe it picks up the manager update on the github or smth? 

### Debug Logs

```powershell
File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/server.py", line 142, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1533, in get_notice
    version_tag = core.get_comfyui_tag()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 77, in get_comfyui_tag
    repo = git.Repo(comfy_path)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/agrande/ComfyUI/.venv/lib/python3.12/site-packages/git/repo/base.py", line 289, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Applications/ComfyUI.app/Contents/Resources/ComfyUI
```

### Browser Logs

N/A

### Settings JSON

N/A

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1013-Bug-ComfyUI-Manager-500-error-after-fetching-updates-1ac6d73d365081778eccc10d6224f38a) by [Unito](https://www.unito.io)

**Comment by robinjhuang** [comment]
@aperepel Which version of Desktop are you on? This should be fixed in the latest version.

**Comment by aperepel** [comment]
Version 0.4.26 (2503047uzec04mv) - it's not fixed there, that's the latest available.

Looking at the code in `manager_core.py` (I haven't yet set up dev workflow):
```python
def get_comfyui_tag():
    repo = git.Repo(comfy_path)
    try:
        return repo.git.describe('--tags')
    except:
        return None
```

Shouldn't the `git.Repo()` call be moved inside the try block? the local path is never a git repo for desktop-installed manager.

**Comment by aperepel** [comment]
I've been updating nodes and it seems to have triggered some refresh. I now see the expected behavior and no error:

<img width="351" alt="Image" src="https://github.com/user-attachments/assets/e9c436f2-5d76-4108-8f57-9b4c73cff6fc" />

**Comment by aperepel** [comment]
Hate to reopen it, but I've just updated to `0.4.27 (250305c7bc5odk1)` and the exact same error is back.
